# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "ben-test-app"
client_id = "beeddfe1e1ae43d86f09cfd44b1502d0"
application_url = "https://pottery-prostate-speakers-chart.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_delivery_customizations"

[auth]
redirect_urls = [
  "https://pottery-prostate-speakers-chart.trycloudflare.com/auth/callback",
  "https://pottery-prostate-speakers-chart.trycloudflare.com/auth/shopify/callback",
  "https://pottery-prostate-speakers-chart.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ben-sparrow.myshopify.com"
